In [336]:
import pandas as pd
import numpy as np
import seaborn as sns


In [337]:
type1=pd.read_csv('train.csv')
type1.head()


id                                              title  Rating maincateg  \
0  16695  Fashionable & Comfortable Bellies For Women  (...     3.9     Women   
1   5120  Combo Pack of 4 Casual Shoes Sneakers For Men ...     3.8       Men   
2  18391         Cilia Mode Leo Sneakers For Women  (White)     4.4     Women   
3    495                            Men Black Sports Sandal     4.2       Men   
4  16408                            Men Green Sports Sandal     3.9       Men   

   platform  price1  actprice1 Offer %  norating1  noreviews1  star_5f  \
0  Flipkart     698        999  30.13%       38.0         7.0     17.0   
1  Flipkart     999       1999  50.03%      531.0        69.0    264.0   
2  Flipkart    2749       4999  45.01%       17.0         4.0     11.0   
3  Flipkart     518        724  15.85%    46413.0      6229.0   1045.0   
4  Flipkart    1379       2299  40.02%       77.0         3.0     35.0   

   star_4f  star_3f  star_2f  star_1f  fulfilled1  
0      9.0      6.0        3        3           0  
1     92.0     73.0       29       73           1  
2      3.0      2.0        1        0           1  
3  12416.0   5352.0      701     4595           1  
4     21.0      7.0        7        7           1

In [338]:
type2=pd.read_csv('test.csv')
print(type2.shape)
type2.head()

(5244, 14)


id                                              title  Rating maincateg  \
0   2242                            Casuals For Men  (Blue)     3.8       Men   
1  20532                           Women Black Flats Sandal     3.9     Women   
2  10648                           Women Gold Wedges Sandal     3.9     Women   
3  20677  Men's Height Increasing High Heel Formal Party...     3.9       Men   
4  12593                             Loafers For Men  (Tan)     3.9       Men   

   platform  actprice1  norating1  noreviews1  star_5f  star_4f  star_3f  \
0  Flipkart        999      27928        3543  14238.0     4295     3457   
1  Flipkart        499       3015         404   1458.0      657      397   
2  Flipkart        999        449          52    229.0       70       71   
3  Flipkart       2999        290          40    141.0       51       49   
4  Flipkart        999       2423         326   1265.0      414      293   

   star_2f  star_1f  fulfilled1  
0     1962   3976.0           1  
1      182    321.0           1  
2       33     46.0           1  
3       17     32.0           1  
4      143    308.0           0

In [339]:
type3=pd.read_csv('Sample__submission.csv')
type3.head()

id  price1
0  19841     193
1  19157     340
2  19445     637
3   8046     679
4   4571     190

In [340]:
type1.shape

(15730, 16)

In [341]:
type1.dtypes

id              int64
title          object
Rating        float64
maincateg      object
platform       object
price1          int64
actprice1       int64
Offer %        object
norating1     float64
noreviews1    float64
star_5f       float64
star_4f       float64
star_3f       float64
star_2f         int64
star_1f         int64
fulfilled1      int64
dtype: object

In [342]:
type1.isnull().sum()

id              0
title           0
Rating          0
maincateg     526
platform        0
price1          0
actprice1       0
Offer %         0
norating1     678
noreviews1    578
star_5f       588
star_4f       539
star_3f       231
star_2f         0
star_1f         0
fulfilled1      0
dtype: int64

In [343]:
type1.drop(['title','id'], axis=1,inplace=True)

In [344]:
from sklearn.preprocessing import OneHotEncoder
type5= pd.get_dummies(type1, columns = ['maincateg', 'platform'])

type5.head()



Rating  price1  actprice1 Offer %  norating1  noreviews1  star_5f  star_4f  \
0     3.9     698        999  30.13%       38.0         7.0     17.0      9.0   
1     3.8     999       1999  50.03%      531.0        69.0    264.0     92.0   
2     4.4    2749       4999  45.01%       17.0         4.0     11.0      3.0   
3     4.2     518        724  15.85%    46413.0      6229.0   1045.0  12416.0   
4     3.9    1379       2299  40.02%       77.0         3.0     35.0     21.0   

   star_3f  star_2f  star_1f  fulfilled1  maincateg_Men  maincateg_Women  \
0      6.0        3        3           0              0                1   
1     73.0       29       73           1              1                0   
2      2.0        1        0           1              0                1   
3   5352.0      701     4595           1              1                0   
4      7.0        7        7           1              1                0   

   platform_Amazon  platform_Flipkart  
0                0                  1  
1                0                  1  
2                0                  1  
3                0                  1  
4                0                  1

In [345]:
for i in range(len(type1)):
    rating=pd.Series((type5['star_5f']*5+type5['star_4f']*4+type5['star_3f']*3+type5['star_2f']*2+type5['star_1f']*1)/(type5['star_5f']+type5['star_4f']+type5['star_3f']+type5['star_2f']+type5['star_1f']))
   

In [346]:
print(type5.head())
print(rating.head())
type5.drop(['star_5f','star_4f','star_3f','star_2f','star_1f'], axis=1,inplace=True)

   Rating  price1  actprice1 Offer %  norating1  noreviews1  star_5f  star_4f  \
0     3.9     698        999  30.13%       38.0         7.0     17.0      9.0   
1     3.8     999       1999  50.03%      531.0        69.0    264.0     92.0   
2     4.4    2749       4999  45.01%       17.0         4.0     11.0      3.0   
3     4.2     518        724  15.85%    46413.0      6229.0   1045.0  12416.0   
4     3.9    1379       2299  40.02%       77.0         3.0     35.0     21.0   

   star_3f  star_2f  star_1f  fulfilled1  maincateg_Men  maincateg_Women  \
0      6.0        3        3           0              0                1   
1     73.0       29       73           1              1                0   
2      2.0        1        0           1              0                1   
3   5352.0      701     4595           1              1                0   
4      7.0        7        7           1              1                0   

   platform_Amazon  platform_Flipkart  
0               

In [347]:
type5.head()

Rating  price1  actprice1 Offer %  norating1  noreviews1  fulfilled1  \
0     3.9     698        999  30.13%       38.0         7.0           0   
1     3.8     999       1999  50.03%      531.0        69.0           1   
2     4.4    2749       4999  45.01%       17.0         4.0           1   
3     4.2     518        724  15.85%    46413.0      6229.0           1   
4     3.9    1379       2299  40.02%       77.0         3.0           1   

   maincateg_Men  maincateg_Women  platform_Amazon  platform_Flipkart  
0              0                1                0                  1  
1              1                0                0                  1  
2              0                1                0                  1  
3              1                0                0                  1  
4              1                0                0                  1

In [388]:
type5.fillna(0,inplace=True)

In [389]:
type5.isnull().sum()

Rating               0
price1               0
actprice1            0
Offer %              0
norating1            0
noreviews1           0
fulfilled1           0
maincateg_Men        0
maincateg_Women      0
platform_Amazon      0
platform_Flipkart    0
dtype: int64

In [390]:
X=type5.drop(['actprice1','Offer %'],axis=1)
y=type5.loc[:,'actprice1']

In [391]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42)

In [392]:
from sklearn.preprocessing import MinMaxScaler

data=['norating1','noreviews1']
features=X[data]
scaler = MinMaxScaler().fit(features.values)
scaled = scaler.transform(features.values)
print((scaled))


type5.head()

[[1.31046684e-04 1.54022179e-04]
 [1.83120497e-03 1.51821862e-03]
 [5.86261480e-05 8.80126738e-05]
 ...
 [0.00000000e+00 3.96057032e-04]
 [2.58644770e-03 1.05395177e-02]
 [2.75887755e-05 2.20031685e-05]]


Rating  price1  actprice1 Offer %  norating1  noreviews1  fulfilled1  \
0     3.9     698        999  30.13%       38.0         7.0           0   
1     3.8     999       1999  50.03%      531.0        69.0           1   
2     4.4    2749       4999  45.01%       17.0         4.0           1   
3     4.2     518        724  15.85%    46413.0      6229.0           1   
4     3.9    1379       2299  40.02%       77.0         3.0           1   

   maincateg_Men  maincateg_Women  platform_Amazon  platform_Flipkart  
0              0                1                0                  1  
1              1                0                0                  1  
2              0                1                0                  1  
3              1                0                0                  1  
4              1                0                0                  1

In [393]:
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

lr=LinearRegression()
type5.fillna(0)
type5.replace([np.inf, -np.inf], np.nan, inplace=True)


lr.fit(X_train,y_train)
pred=lr.predict(X_test)


In [394]:
type5.isnull().sum()

Rating               0
price1               0
actprice1            0
Offer %              0
norating1            0
noreviews1           0
fulfilled1           0
maincateg_Men        0
maincateg_Women      0
platform_Amazon      0
platform_Flipkart    0
dtype: int64

In [395]:
import math
MSE=np.square(np.subtract(pred,y_test)).mean()
RMSE=math.sqrt(MSE)
print(RMSE)

556.662702889039


In [396]:
(y_test.shape)

(5191,)

In [451]:
import xgboost as xgb
XGB = xgb.XGBRegressor(verbosity=3,objective='reg:squarederror') 
XGB.fit(X_train,y_train)
XGB.predict(X_test)
pred_1=XGB.predict(X_test)
print(pred_1)

[00:03:41] ======== Monitor (0): Learner ========
[00:03:41] Configure: 0.000296s, 1 calls @ 296us

[00:03:41] ======== Monitor (0): GBTree ========
[00:03:41] ======== Monitor (0): TreePruner ========
[00:03:41] DEBUG: C:/Users/Administrator/workspace/xgboost-win64_release_1.6.0/src/gbm/gbtree.cc:155: Using tree method: 2
[00:03:41] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.6.0/src/tree/updater_prune.cc:101: tree pruning end, 86 extra nodes, 0 pruned nodes, max_depth=6
[00:03:41] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.6.0/src/tree/updater_prune.cc:101: tree pruning end, 94 extra nodes, 0 pruned nodes, max_depth=6
[00:03:41] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.6.0/src/tree/updater_prune.cc:101: tree pruning end, 104 extra nodes, 0 pruned nodes, max_depth=6
[00:03:41] INFO: C:/Users/Administrator/workspace/xgboost-win64_release_1.6.0/src/tree/updater_prune.cc:101: tree pruning end, 108 extra nodes, 0 pruned nodes, m

In [452]:
MSE = np.square(np.subtract(pred_1,y_test)).mean()
RMSE=math.sqrt(MSE)
print(RMSE)

462.23997321912833


In [453]:
mms = MinMaxScaler()
type4= pd.get_dummies(type2, columns = ['maincateg', 'platform'])

type4.drop(['star_5f','star_4f','star_3f','star_2f','star_1f','title','actprice1'], axis=1,inplace=True)
data=['norating1','noreviews1']
features=type4[data]
scaler = MinMaxScaler().fit(features.values)
scaled = scaler.transform(features.values)
print((scaled))
pred_2=XGB.predict(type4)

[[9.63092988e-02 7.79572258e-02]
 [1.03941070e-02 8.88928006e-03]
 [1.54497676e-03 1.14416476e-03]
 ...
 [4.41077070e-03 2.97042774e-03]
 [1.67809306e-02 1.26298187e-02]
 [2.41402618e-05 1.10015842e-04]]


In [454]:
print(pred_2)

[556.22327 566.57404 459.32254 ... 820.19025 566.02814 217.19855]


In [455]:
id=type4['id'].values

In [456]:
df=pd.DataFrame({'id':id, 'price1':pred_2})

In [457]:
df.head()

id      price1
0   2242  556.223267
1  20532  566.574036
2  10648  459.322540
3  20677  260.574097
4  12593  732.593201

In [432]:
df.shape

(5244, 2)

In [406]:
from sklearn import svm
regr = svm.SVR()
regr.fit(X_train, y_train)
regr.predict(X_test)
pred_1=regr.predict(X_test)
print(pred_1)

[ 997.29220816 1009.51750599 1025.14824198 ...  995.58774505  992.82477917
  997.634342  ]


In [407]:
MSE = np.square(np.subtract(pred_1,y_test)).mean()
RMSE=math.sqrt(MSE)
print(RMSE)

1246.907167359092


In [408]:
mms = MinMaxScaler()
type4= pd.get_dummies(type2, columns = ['maincateg', 'platform'])

type4.drop(['star_5f','star_4f','star_3f','star_2f','star_1f','title','actprice1'], axis=1,inplace=True)
data=['norating1','noreviews1']
features=type4[data]
scaler = MinMaxScaler().fit(features.values)
scaled = scaler.transform(features.values)
print((scaled))
type4['Rating'].fillna(int(type4['Rating'].mean()), inplace = True)
pred_3=regr.predict(type4)


[[9.63092988e-02 7.79572258e-02]
 [1.03941070e-02 8.88928006e-03]
 [1.54497676e-03 1.14416476e-03]
 ...
 [4.41077070e-03 2.97042774e-03]
 [1.67809306e-02 1.26298187e-02]
 [2.41402618e-05 1.10015842e-04]]


C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- id
Feature names seen at fit time, yet now missing:
- price1

  warnings.warn(message, FutureWarning)


In [409]:
type4.isnull().sum()

id                   0
Rating               0
norating1            0
noreviews1           0
fulfilled1           0
maincateg_Men        0
maincateg_Women      0
platform_Amazon      0
platform_Flipkart    0
dtype: int64

In [410]:
print(pred_3)

[ 998.47089527 1002.82642221  994.48110003 ... 1002.31026495  987.55520017
  998.70526456]


In [411]:
id=type4['id'].values

In [434]:
df=pd.DataFrame({'id':id, 'price1':pred_3})

In [413]:
from sklearn.linear_model import LogisticRegression

In [414]:
Lr=LogisticRegression()
type5.replace([np.inf, -np.inf], np.nan, inplace=True)


Lr.fit(X_train,y_train)
pred=lr.predict(X_test)
mms = MinMaxScaler()
type4= pd.get_dummies(type2, columns = ['maincateg', 'platform'])

type4.drop(['star_5f','star_4f','star_3f','star_2f','star_1f','title','actprice1'], axis=1,inplace=True)
data=['norating1','noreviews1']
features=type4[data]
scaler = MinMaxScaler().fit(features.values)
scaled = scaler.transform(features.values)
print((scaled))
type4['Rating'].fillna(int(type4['Rating'].mean()), inplace = True)
pred_4=Lr.predict(type4)

[[9.63092988e-02 7.79572258e-02]
 [1.03941070e-02 8.88928006e-03]
 [1.54497676e-03 1.14416476e-03]
 ...
 [4.41077070e-03 2.97042774e-03]
 [1.67809306e-02 1.26298187e-02]
 [2.41402618e-05 1.10015842e-04]]


C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- id
Feature names seen at fit time, yet now missing:
- price1

  warnings.warn(message, FutureWarning)


In [415]:
print(pred_4)

[999 999 999 ... 999 999 999]


In [416]:
id=type4['id'].values

In [417]:
df=pd.DataFrame({'id':id, 'price1':pred_4})

In [418]:
df.to_csv('file4.csv', index=False)

In [501]:
from sklearn.ensemble import RandomForestRegressor 
clf = RandomForestRegressor(max_depth=100, random_state=5)
clf.fit(X_train,y_train)
pred=clf.predict(X_test)
mms = MinMaxScaler()
type4= pd.get_dummies(type2, columns = ['maincateg', 'platform'])

type4.drop(['star_5f','star_4f','star_3f','star_2f','star_1f','title','actprice1'], axis=1,inplace=True)
data=['norating1','noreviews1']
features=type4[data]
scaler = MinMaxScaler().fit(features.values)
scaled = scaler.transform(features.values)
print((scaled))
type4['Rating'].fillna(int(type4['Rating'].mean()), inplace = True)
pred_5=clf.predict(type4)

[[9.63092988e-02 7.79572258e-02]
 [1.03941070e-02 8.88928006e-03]
 [1.54497676e-03 1.14416476e-03]
 ...
 [4.41077070e-03 2.97042774e-03]
 [1.67809306e-02 1.26298187e-02]
 [2.41402618e-05 1.10015842e-04]]


C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- id
Feature names seen at fit time, yet now missing:
- price1

  warnings.warn(message, FutureWarning)


In [502]:
print(pred_5)

[505.1260303  489.57       574.54       ... 590.87       438.95666667
 644.64      ]


In [503]:
id=type4['id'].values

In [1]:
df=pd.DataFrame({'id':id, 'price1':pred_2})

NameError: name 'pd' is not defined

In [505]:
df.to_csv('file12.csv', index=False)